# set default build target for rp2040
[build]
target = "thumbv6m-none-eabi"

# upload binary to rp2040 instead of running on host
#[target.thumbv6m-none-eabi]
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner =  "probe-run --chip RP2040"
#runner = "elf2uf2-rs -s"
runner = "elf2uf2-rs -sd"

# use appropriate memory layout
#rustflags = ["-C", "link-arg=-Tlink.x"]

[env]
DEFMT_LOG = "debug"